//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Misha
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Task
    {
        public int ID { get; set; }
        public Nullable<int> Task_id { get; set; }
        public Nullable<int> Student_id { get; set; }
        public Nullable<int> Bal { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Tasks Tasks { get; set; }
    }
}
